name: 01-BuildingBlocks

on: 
  push: 
    branches: 
      - main

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Succed step
        run: |
          echo "I will succed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"
